<?php
namespace OS\Neos\BootstrapTheme\DataSource;

use TYPO3\Neos\Service\DataSource\AbstractDataSource;
use TYPO3\TYPO3CR\Domain\Model\NodeInterface;

class FontAwesomeIconDataSource extends AbstractDataSource {

    /**
     * @var string
     */
    static protected $identifier = 'os-font-awesome-icons';

    /**
     * Get data
     *
     * @param NodeInterface $node The node that is currently edited (optional)
     * @param array $arguments Additional arguments (key / value)
     * @return array JSON serializable data
     */
    public function getData(NodeInterface $node = NULL, array $arguments)
    {
        return array(
            array("value" => "fa-500px", "label" => "500px", "icon" => "icon-500px"),
            array("value" => "fa-address-book", "label" => "Address Book", "icon" => "icon-address-book"),
            array("value" => "fa-address-book-o", "label" => "Address Book O", "icon" => "icon-address-book-o"),
            array("value" => "fa-address-card", "label" => "Address Card", "icon" => "icon-address-card"),
            array("value" => "fa-address-card-o", "label" => "Address Card O", "icon" => "icon-address-card-o"),
            array("value" => "fa-adjust", "label" => "Adjust", "icon" => "icon-adjust"),
            array("value" => "fa-adn", "label" => "Adn", "icon" => "icon-adn"),
            array("value" => "fa-align-center", "label" => "Align Center", "icon" => "icon-align-center"),
            array("value" => "fa-align-justify", "label" => "Align Justify", "icon" => "icon-align-justify"),
            array("value" => "fa-align-left", "label" => "Align Left", "icon" => "icon-align-left"),
            array("value" => "fa-align-right", "label" => "Align Right", "icon" => "icon-align-right"),
            array("value" => "fa-amazon", "label" => "Amazon", "icon" => "icon-amazon"),
            array("value" => "fa-ambulance", "label" => "Ambulance", "icon" => "icon-ambulance"),
            array("value" => "fa-american-sign-language-interpreting", "label" => "American Sign Language Interpreting", "icon" => "icon-american-sign-language-interpreting"),
            array("value" => "fa-anchor", "label" => "Anchor", "icon" => "icon-anchor"),
            array("value" => "fa-android", "label" => "Android", "icon" => "icon-android"),
            array("value" => "fa-angellist", "label" => "Angellist", "icon" => "icon-angellist"),
            array("value" => "fa-angle-double-down", "label" => "Angle Double Down", "icon" => "icon-angle-double-down"),
            array("value" => "fa-angle-double-left", "label" => "Angle Double Left", "icon" => "icon-angle-double-left"),
            array("value" => "fa-angle-double-right", "label" => "Angle Double Right", "icon" => "icon-angle-double-right"),
            array("value" => "fa-angle-double-up", "label" => "Angle Double Up", "icon" => "icon-angle-double-up"),
            array("value" => "fa-angle-down", "label" => "Angle Down", "icon" => "icon-angle-down"),
            array("value" => "fa-angle-left", "label" => "Angle Left", "icon" => "icon-angle-left"),
            array("value" => "fa-angle-right", "label" => "Angle Right", "icon" => "icon-angle-right"),
            array("value" => "fa-angle-up", "label" => "Angle Up", "icon" => "icon-angle-up"),
            array("value" => "fa-apple", "label" => "Apple", "icon" => "icon-apple"),
            array("value" => "fa-archive", "label" => "Archive", "icon" => "icon-archive"),
            array("value" => "fa-area-chart", "label" => "Area Chart", "icon" => "icon-area-chart"),
            array("value" => "fa-arrow-circle-down", "label" => "Arrow Circle Down", "icon" => "icon-arrow-circle-down"),
            array("value" => "fa-arrow-circle-left", "label" => "Arrow Circle Left", "icon" => "icon-arrow-circle-left"),
            array("value" => "fa-arrow-circle-o-down", "label" => "Arrow Circle O Down", "icon" => "icon-arrow-circle-o-down"),
            array("value" => "fa-arrow-circle-o-left", "label" => "Arrow Circle O Left", "icon" => "icon-arrow-circle-o-left"),
            array("value" => "fa-arrow-circle-o-right", "label" => "Arrow Circle O Right", "icon" => "icon-arrow-circle-o-right"),
            array("value" => "fa-arrow-circle-o-up", "label" => "Arrow Circle O Up", "icon" => "icon-arrow-circle-o-up"),
            array("value" => "fa-arrow-circle-right", "label" => "Arrow Circle Right", "icon" => "icon-arrow-circle-right"),
            array("value" => "fa-arrow-circle-up", "label" => "Arrow Circle Up", "icon" => "icon-arrow-circle-up"),
            array("value" => "fa-arrow-down", "label" => "Arrow Down", "icon" => "icon-arrow-down"),
            array("value" => "fa-arrow-left", "label" => "Arrow Left", "icon" => "icon-arrow-left"),
            array("value" => "fa-arrow-right", "label" => "Arrow Right", "icon" => "icon-arrow-right"),
            array("value" => "fa-arrow-up", "label" => "Arrow Up", "icon" => "icon-arrow-up"),
            array("value" => "fa-arrows", "label" => "Arrows", "icon" => "icon-arrows"),
            array("value" => "fa-arrows-alt", "label" => "Arrows Alt", "icon" => "icon-arrows-alt"),
            array("value" => "fa-arrows-h", "label" => "Arrows H", "icon" => "icon-arrows-h"),
            array("value" => "fa-arrows-v", "label" => "Arrows V", "icon" => "icon-arrows-v"),
            array("value" => "fa-assistive-listening-systems", "label" => "Assistive Listening Systems", "icon" => "icon-assistive-listening-systems"),
            array("value" => "fa-asterisk", "label" => "Asterisk", "icon" => "icon-asterisk"),
            array("value" => "fa-at", "label" => "At", "icon" => "icon-at"),
            array("value" => "fa-audio-description", "label" => "Audio Description", "icon" => "icon-audio-description"),
            array("value" => "fa-backward", "label" => "Backward", "icon" => "icon-backward"),
            array("value" => "fa-balance-scale", "label" => "Balance Scale", "icon" => "icon-balance-scale"),
            array("value" => "fa-ban", "label" => "Ban", "icon" => "icon-ban"),
            array("value" => "fa-bandcamp", "label" => "Bandcamp", "icon" => "icon-bandcamp"),
            array("value" => "fa-bar-chart", "label" => "Bar Chart", "icon" => "icon-bar-chart"),
            array("value" => "fa-barcode", "label" => "Barcode", "icon" => "icon-barcode"),
            array("value" => "fa-bars", "label" => "Bars", "icon" => "icon-bars"),
            array("value" => "fa-bath", "label" => "Bath", "icon" => "icon-bath"),
            array("value" => "fa-battery-empty", "label" => "Battery Empty", "icon" => "icon-battery-empty"),
            array("value" => "fa-battery-full", "label" => "Battery Full", "icon" => "icon-battery-full"),
            array("value" => "fa-battery-half", "label" => "Battery Half", "icon" => "icon-battery-half"),
            array("value" => "fa-battery-quarter", "label" => "Battery Quarter", "icon" => "icon-battery-quarter"),
            array("value" => "fa-battery-three-quarters", "label" => "Battery Three Quarters", "icon" => "icon-battery-three-quarters"),
            array("value" => "fa-bed", "label" => "Bed", "icon" => "icon-bed"),
            array("value" => "fa-beer", "label" => "Beer", "icon" => "icon-beer"),
            array("value" => "fa-behance", "label" => "Behance", "icon" => "icon-behance"),
            array("value" => "fa-behance-square", "label" => "Behance Square", "icon" => "icon-behance-square"),
            array("value" => "fa-bell", "label" => "Bell", "icon" => "icon-bell"),
            array("value" => "fa-bell-o", "label" => "Bell O", "icon" => "icon-bell-o"),
            array("value" => "fa-bell-slash", "label" => "Bell Slash", "icon" => "icon-bell-slash"),
            array("value" => "fa-bell-slash-o", "label" => "Bell Slash O", "icon" => "icon-bell-slash-o"),
            array("value" => "fa-bicycle", "label" => "Bicycle", "icon" => "icon-bicycle"),
            array("value" => "fa-binoculars", "label" => "Binoculars", "icon" => "icon-binoculars"),
            array("value" => "fa-birthday-cake", "label" => "Birthday Cake", "icon" => "icon-birthday-cake"),
            array("value" => "fa-bitbucket", "label" => "Bitbucket", "icon" => "icon-bitbucket"),
            array("value" => "fa-bitbucket-square", "label" => "Bitbucket Square", "icon" => "icon-bitbucket-square"),
            array("value" => "fa-black-tie", "label" => "Black Tie", "icon" => "icon-black-tie"),
            array("value" => "fa-blind", "label" => "Blind", "icon" => "icon-blind"),
            array("value" => "fa-bluetooth", "label" => "Bluetooth", "icon" => "icon-bluetooth"),
            array("value" => "fa-bluetooth-b", "label" => "Bluetooth B", "icon" => "icon-bluetooth-b"),
            array("value" => "fa-bold", "label" => "Bold", "icon" => "icon-bold"),
            array("value" => "fa-bolt", "label" => "Bolt", "icon" => "icon-bolt"),
            array("value" => "fa-bomb", "label" => "Bomb", "icon" => "icon-bomb"),
            array("value" => "fa-book", "label" => "Book", "icon" => "icon-book"),
            array("value" => "fa-bookmark", "label" => "Bookmark", "icon" => "icon-bookmark"),
            array("value" => "fa-bookmark-o", "label" => "Bookmark O", "icon" => "icon-bookmark-o"),
            array("value" => "fa-braille", "label" => "Braille", "icon" => "icon-braille"),
            array("value" => "fa-briefcase", "label" => "Briefcase", "icon" => "icon-briefcase"),
            array("value" => "fa-btc", "label" => "Btc", "icon" => "icon-btc"),
            array("value" => "fa-bug", "label" => "Bug", "icon" => "icon-bug"),
            array("value" => "fa-building", "label" => "Building", "icon" => "icon-building"),
            array("value" => "fa-building-o", "label" => "Building O", "icon" => "icon-building-o"),
            array("value" => "fa-bullhorn", "label" => "Bullhorn", "icon" => "icon-bullhorn"),
            array("value" => "fa-bullseye", "label" => "Bullseye", "icon" => "icon-bullseye"),
            array("value" => "fa-bus", "label" => "Bus", "icon" => "icon-bus"),
            array("value" => "fa-buysellads", "label" => "Buysellads", "icon" => "icon-buysellads"),
            array("value" => "fa-calculator", "label" => "Calculator", "icon" => "icon-calculator"),
            array("value" => "fa-calendar", "label" => "Calendar", "icon" => "icon-calendar"),
            array("value" => "fa-calendar-check-o", "label" => "Calendar Check O", "icon" => "icon-calendar-check-o"),
            array("value" => "fa-calendar-minus-o", "label" => "Calendar Minus O", "icon" => "icon-calendar-minus-o"),
            array("value" => "fa-calendar-o", "label" => "Calendar O", "icon" => "icon-calendar-o"),
            array("value" => "fa-calendar-plus-o", "label" => "Calendar Plus O", "icon" => "icon-calendar-plus-o"),
            array("value" => "fa-calendar-times-o", "label" => "Calendar Times O", "icon" => "icon-calendar-times-o"),
            array("value" => "fa-camera", "label" => "Camera", "icon" => "icon-camera"),
            array("value" => "fa-camera-retro", "label" => "Camera Retro", "icon" => "icon-camera-retro"),
            array("value" => "fa-car", "label" => "Car", "icon" => "icon-car"),
            array("value" => "fa-caret-down", "label" => "Caret Down", "icon" => "icon-caret-down"),
            array("value" => "fa-caret-left", "label" => "Caret Left", "icon" => "icon-caret-left"),
            array("value" => "fa-caret-right", "label" => "Caret Right", "icon" => "icon-caret-right"),
            array("value" => "fa-caret-square-o-down", "label" => "Caret Square O Down", "icon" => "icon-caret-square-o-down"),
            array("value" => "fa-caret-square-o-left", "label" => "Caret Square O Left", "icon" => "icon-caret-square-o-left"),
            array("value" => "fa-caret-square-o-right", "label" => "Caret Square O Right", "icon" => "icon-caret-square-o-right"),
            array("value" => "fa-caret-square-o-up", "label" => "Caret Square O Up", "icon" => "icon-caret-square-o-up"),
            array("value" => "fa-caret-up", "label" => "Caret Up", "icon" => "icon-caret-up"),
            array("value" => "fa-cart-arrow-down", "label" => "Cart Arrow Down", "icon" => "icon-cart-arrow-down"),
            array("value" => "fa-cart-plus", "label" => "Cart Plus", "icon" => "icon-cart-plus"),
            array("value" => "fa-cc", "label" => "Cc", "icon" => "icon-cc"),
            array("value" => "fa-cc-amex", "label" => "Cc Amex", "icon" => "icon-cc-amex"),
            array("value" => "fa-cc-diners-club", "label" => "Cc Diners Club", "icon" => "icon-cc-diners-club"),
            array("value" => "fa-cc-discover", "label" => "Cc Discover", "icon" => "icon-cc-discover"),
            array("value" => "fa-cc-jcb", "label" => "Cc Jcb", "icon" => "icon-cc-jcb"),
            array("value" => "fa-cc-mastercard", "label" => "Cc Mastercard", "icon" => "icon-cc-mastercard"),
            array("value" => "fa-cc-paypal", "label" => "Cc Paypal", "icon" => "icon-cc-paypal"),
            array("value" => "fa-cc-stripe", "label" => "Cc Stripe", "icon" => "icon-cc-stripe"),
            array("value" => "fa-cc-visa", "label" => "Cc Visa", "icon" => "icon-cc-visa"),
            array("value" => "fa-certificate", "label" => "Certificate", "icon" => "icon-certificate"),
            array("value" => "fa-chain-broken", "label" => "Chain Broken", "icon" => "icon-chain-broken"),
            array("value" => "fa-check", "label" => "Check", "icon" => "icon-check"),
            array("value" => "fa-check-circle", "label" => "Check Circle", "icon" => "icon-check-circle"),
            array("value" => "fa-check-circle-o", "label" => "Check Circle O", "icon" => "icon-check-circle-o"),
            array("value" => "fa-check-square", "label" => "Check Square", "icon" => "icon-check-square"),
            array("value" => "fa-check-square-o", "label" => "Check Square O", "icon" => "icon-check-square-o"),
            array("value" => "fa-chevron-circle-down", "label" => "Chevron Circle Down", "icon" => "icon-chevron-circle-down"),
            array("value" => "fa-chevron-circle-left", "label" => "Chevron Circle Left", "icon" => "icon-chevron-circle-left"),
            array("value" => "fa-chevron-circle-right", "label" => "Chevron Circle Right", "icon" => "icon-chevron-circle-right"),
            array("value" => "fa-chevron-circle-up", "label" => "Chevron Circle Up", "icon" => "icon-chevron-circle-up"),
            array("value" => "fa-chevron-down", "label" => "Chevron Down", "icon" => "icon-chevron-down"),
            array("value" => "fa-chevron-left", "label" => "Chevron Left", "icon" => "icon-chevron-left"),
            array("value" => "fa-chevron-right", "label" => "Chevron Right", "icon" => "icon-chevron-right"),
            array("value" => "fa-chevron-up", "label" => "Chevron Up", "icon" => "icon-chevron-up"),
            array("value" => "fa-child", "label" => "Child", "icon" => "icon-child"),
            array("value" => "fa-chrome", "label" => "Chrome", "icon" => "icon-chrome"),
            array("value" => "fa-circle", "label" => "Circle", "icon" => "icon-circle"),
            array("value" => "fa-circle-o", "label" => "Circle O", "icon" => "icon-circle-o"),
            array("value" => "fa-circle-o-notch", "label" => "Circle O Notch", "icon" => "icon-circle-o-notch"),
            array("value" => "fa-circle-thin", "label" => "Circle Thin", "icon" => "icon-circle-thin"),
            array("value" => "fa-clipboard", "label" => "Clipboard", "icon" => "icon-clipboard"),
            array("value" => "fa-clock-o", "label" => "Clock O", "icon" => "icon-clock-o"),
            array("value" => "fa-clone", "label" => "Clone", "icon" => "icon-clone"),
            array("value" => "fa-cloud", "label" => "Cloud", "icon" => "icon-cloud"),
            array("value" => "fa-cloud-download", "label" => "Cloud Download", "icon" => "icon-cloud-download"),
            array("value" => "fa-cloud-upload", "label" => "Cloud Upload", "icon" => "icon-cloud-upload"),
            array("value" => "fa-code", "label" => "Code", "icon" => "icon-code"),
            array("value" => "fa-code-fork", "label" => "Code Fork", "icon" => "icon-code-fork"),
            array("value" => "fa-codepen", "label" => "Codepen", "icon" => "icon-codepen"),
            array("value" => "fa-codiepie", "label" => "Codiepie", "icon" => "icon-codiepie"),
            array("value" => "fa-coffee", "label" => "Coffee", "icon" => "icon-coffee"),
            array("value" => "fa-cog", "label" => "Cog", "icon" => "icon-cog"),
            array("value" => "fa-cogs", "label" => "Cogs", "icon" => "icon-cogs"),
            array("value" => "fa-columns", "label" => "Columns", "icon" => "icon-columns"),
            array("value" => "fa-comment", "label" => "Comment", "icon" => "icon-comment"),
            array("value" => "fa-comment-o", "label" => "Comment O", "icon" => "icon-comment-o"),
            array("value" => "fa-commenting", "label" => "Commenting", "icon" => "icon-commenting"),
            array("value" => "fa-commenting-o", "label" => "Commenting O", "icon" => "icon-commenting-o"),
            array("value" => "fa-comments", "label" => "Comments", "icon" => "icon-comments"),
            array("value" => "fa-comments-o", "label" => "Comments O", "icon" => "icon-comments-o"),
            array("value" => "fa-compass", "label" => "Compass", "icon" => "icon-compass"),
            array("value" => "fa-compress", "label" => "Compress", "icon" => "icon-compress"),
            array("value" => "fa-connectdevelop", "label" => "Connectdevelop", "icon" => "icon-connectdevelop"),
            array("value" => "fa-contao", "label" => "Contao", "icon" => "icon-contao"),
            array("value" => "fa-copyright", "label" => "Copyright", "icon" => "icon-copyright"),
            array("value" => "fa-creative-commons", "label" => "Creative Commons", "icon" => "icon-creative-commons"),
            array("value" => "fa-credit-card", "label" => "Credit Card", "icon" => "icon-credit-card"),
            array("value" => "fa-credit-card-alt", "label" => "Credit Card Alt", "icon" => "icon-credit-card-alt"),
            array("value" => "fa-crop", "label" => "Crop", "icon" => "icon-crop"),
            array("value" => "fa-crosshairs", "label" => "Crosshairs", "icon" => "icon-crosshairs"),
            array("value" => "fa-css3", "label" => "Css3", "icon" => "icon-css3"),
            array("value" => "fa-cube", "label" => "Cube", "icon" => "icon-cube"),
            array("value" => "fa-cubes", "label" => "Cubes", "icon" => "icon-cubes"),
            array("value" => "fa-cutlery", "label" => "Cutlery", "icon" => "icon-cutlery"),
            array("value" => "fa-dashcube", "label" => "Dashcube", "icon" => "icon-dashcube"),
            array("value" => "fa-database", "label" => "Database", "icon" => "icon-database"),
            array("value" => "fa-deaf", "label" => "Deaf", "icon" => "icon-deaf"),
            array("value" => "fa-delicious", "label" => "Delicious", "icon" => "icon-delicious"),
            array("value" => "fa-desktop", "label" => "Desktop", "icon" => "icon-desktop"),
            array("value" => "fa-deviantart", "label" => "Deviantart", "icon" => "icon-deviantart"),
            array("value" => "fa-diamond", "label" => "Diamond", "icon" => "icon-diamond"),
            array("value" => "fa-digg", "label" => "Digg", "icon" => "icon-digg"),
            array("value" => "fa-dot-circle-o", "label" => "Dot Circle O", "icon" => "icon-dot-circle-o"),
            array("value" => "fa-download", "label" => "Download", "icon" => "icon-download"),
            array("value" => "fa-dribbble", "label" => "Dribbble", "icon" => "icon-dribbble"),
            array("value" => "fa-dropbox", "label" => "Dropbox", "icon" => "icon-dropbox"),
            array("value" => "fa-drupal", "label" => "Drupal", "icon" => "icon-drupal"),
            array("value" => "fa-edge", "label" => "Edge", "icon" => "icon-edge"),
            array("value" => "fa-eercast", "label" => "Eercast", "icon" => "icon-eercast"),
            array("value" => "fa-eject", "label" => "Eject", "icon" => "icon-eject"),
            array("value" => "fa-ellipsis-h", "label" => "Ellipsis H", "icon" => "icon-ellipsis-h"),
            array("value" => "fa-ellipsis-v", "label" => "Ellipsis V", "icon" => "icon-ellipsis-v"),
            array("value" => "fa-empire", "label" => "Empire", "icon" => "icon-empire"),
            array("value" => "fa-envelope", "label" => "Envelope", "icon" => "icon-envelope"),
            array("value" => "fa-envelope-o", "label" => "Envelope O", "icon" => "icon-envelope-o"),
            array("value" => "fa-envelope-open", "label" => "Envelope Open", "icon" => "icon-envelope-open"),
            array("value" => "fa-envelope-open-o", "label" => "Envelope Open O", "icon" => "icon-envelope-open-o"),
            array("value" => "fa-envelope-square", "label" => "Envelope Square", "icon" => "icon-envelope-square"),
            array("value" => "fa-envira", "label" => "Envira", "icon" => "icon-envira"),
            array("value" => "fa-eraser", "label" => "Eraser", "icon" => "icon-eraser"),
            array("value" => "fa-etsy", "label" => "Etsy", "icon" => "icon-etsy"),
            array("value" => "fa-eur", "label" => "Eur", "icon" => "icon-eur"),
            array("value" => "fa-exchange", "label" => "Exchange", "icon" => "icon-exchange"),
            array("value" => "fa-exclamation", "label" => "Exclamation", "icon" => "icon-exclamation"),
            array("value" => "fa-exclamation-circle", "label" => "Exclamation Circle", "icon" => "icon-exclamation-circle"),
            array("value" => "fa-exclamation-triangle", "label" => "Exclamation Triangle", "icon" => "icon-exclamation-triangle"),
            array("value" => "fa-expand", "label" => "Expand", "icon" => "icon-expand"),
            array("value" => "fa-expeditedssl", "label" => "Expeditedssl", "icon" => "icon-expeditedssl"),
            array("value" => "fa-external-link", "label" => "External Link", "icon" => "icon-external-link"),
            array("value" => "fa-external-link-square", "label" => "External Link Square", "icon" => "icon-external-link-square"),
            array("value" => "fa-eye", "label" => "Eye", "icon" => "icon-eye"),
            array("value" => "fa-eye-slash", "label" => "Eye Slash", "icon" => "icon-eye-slash"),
            array("value" => "fa-eyedropper", "label" => "Eyedropper", "icon" => "icon-eyedropper"),
            array("value" => "fa-facebook", "label" => "Facebook", "icon" => "icon-facebook"),
            array("value" => "fa-facebook-official", "label" => "Facebook Official", "icon" => "icon-facebook-official"),
            array("value" => "fa-facebook-square", "label" => "Facebook Square", "icon" => "icon-facebook-square"),
            array("value" => "fa-fast-backward", "label" => "Fast Backward", "icon" => "icon-fast-backward"),
            array("value" => "fa-fast-forward", "label" => "Fast Forward", "icon" => "icon-fast-forward"),
            array("value" => "fa-fax", "label" => "Fax", "icon" => "icon-fax"),
            array("value" => "fa-female", "label" => "Female", "icon" => "icon-female"),
            array("value" => "fa-fighter-jet", "label" => "Fighter Jet", "icon" => "icon-fighter-jet"),
            array("value" => "fa-file", "label" => "File", "icon" => "icon-file"),
            array("value" => "fa-file-archive-o", "label" => "File Archive O", "icon" => "icon-file-archive-o"),
            array("value" => "fa-file-audio-o", "label" => "File Audio O", "icon" => "icon-file-audio-o"),
            array("value" => "fa-file-code-o", "label" => "File Code O", "icon" => "icon-file-code-o"),
            array("value" => "fa-file-excel-o", "label" => "File Excel O", "icon" => "icon-file-excel-o"),
            array("value" => "fa-file-image-o", "label" => "File Image O", "icon" => "icon-file-image-o"),
            array("value" => "fa-file-o", "label" => "File O", "icon" => "icon-file-o"),
            array("value" => "fa-file-pdf-o", "label" => "File Pdf O", "icon" => "icon-file-pdf-o"),
            array("value" => "fa-file-powerpoint-o", "label" => "File Powerpoint O", "icon" => "icon-file-powerpoint-o"),
            array("value" => "fa-file-text", "label" => "File Text", "icon" => "icon-file-text"),
            array("value" => "fa-file-text-o", "label" => "File Text O", "icon" => "icon-file-text-o"),
            array("value" => "fa-file-video-o", "label" => "File Video O", "icon" => "icon-file-video-o"),
            array("value" => "fa-file-word-o", "label" => "File Word O", "icon" => "icon-file-word-o"),
            array("value" => "fa-files-o", "label" => "Files O", "icon" => "icon-files-o"),
            array("value" => "fa-film", "label" => "Film", "icon" => "icon-film"),
            array("value" => "fa-filter", "label" => "Filter", "icon" => "icon-filter"),
            array("value" => "fa-fire", "label" => "Fire", "icon" => "icon-fire"),
            array("value" => "fa-fire-extinguisher", "label" => "Fire Extinguisher", "icon" => "icon-fire-extinguisher"),
            array("value" => "fa-firefox", "label" => "Firefox", "icon" => "icon-firefox"),
            array("value" => "fa-first-order", "label" => "First Order", "icon" => "icon-first-order"),
            array("value" => "fa-flag", "label" => "Flag", "icon" => "icon-flag"),
            array("value" => "fa-flag-checkered", "label" => "Flag Checkered", "icon" => "icon-flag-checkered"),
            array("value" => "fa-flag-o", "label" => "Flag O", "icon" => "icon-flag-o"),
            array("value" => "fa-flask", "label" => "Flask", "icon" => "icon-flask"),
            array("value" => "fa-flickr", "label" => "Flickr", "icon" => "icon-flickr"),
            array("value" => "fa-floppy-o", "label" => "Floppy O", "icon" => "icon-floppy-o"),
            array("value" => "fa-folder", "label" => "Folder", "icon" => "icon-folder"),
            array("value" => "fa-folder-o", "label" => "Folder O", "icon" => "icon-folder-o"),
            array("value" => "fa-folder-open", "label" => "Folder Open", "icon" => "icon-folder-open"),
            array("value" => "fa-folder-open-o", "label" => "Folder Open O", "icon" => "icon-folder-open-o"),
            array("value" => "fa-font", "label" => "Font", "icon" => "icon-font"),
            array("value" => "fa-font-awesome", "label" => "Font Awesome", "icon" => "icon-font-awesome"),
            array("value" => "fa-fonticons", "label" => "Fonticons", "icon" => "icon-fonticons"),
            array("value" => "fa-fort-awesome", "label" => "Fort Awesome", "icon" => "icon-fort-awesome"),
            array("value" => "fa-forumbee", "label" => "Forumbee", "icon" => "icon-forumbee"),
            array("value" => "fa-forward", "label" => "Forward", "icon" => "icon-forward"),
            array("value" => "fa-foursquare", "label" => "Foursquare", "icon" => "icon-foursquare"),
            array("value" => "fa-free-code-camp", "label" => "Free Code Camp", "icon" => "icon-free-code-camp"),
            array("value" => "fa-frown-o", "label" => "Frown O", "icon" => "icon-frown-o"),
            array("value" => "fa-futbol-o", "label" => "Futbol O", "icon" => "icon-futbol-o"),
            array("value" => "fa-gamepad", "label" => "Gamepad", "icon" => "icon-gamepad"),
            array("value" => "fa-gavel", "label" => "Gavel", "icon" => "icon-gavel"),
            array("value" => "fa-gbp", "label" => "Gbp", "icon" => "icon-gbp"),
            array("value" => "fa-genderless", "label" => "Genderless", "icon" => "icon-genderless"),
            array("value" => "fa-get-pocket", "label" => "Get Pocket", "icon" => "icon-get-pocket"),
            array("value" => "fa-gg", "label" => "Gg", "icon" => "icon-gg"),
            array("value" => "fa-gg-circle", "label" => "Gg Circle", "icon" => "icon-gg-circle"),
            array("value" => "fa-gift", "label" => "Gift", "icon" => "icon-gift"),
            array("value" => "fa-git", "label" => "Git", "icon" => "icon-git"),
            array("value" => "fa-git-square", "label" => "Git Square", "icon" => "icon-git-square"),
            array("value" => "fa-github", "label" => "Github", "icon" => "icon-github"),
            array("value" => "fa-github-alt", "label" => "Github Alt", "icon" => "icon-github-alt"),
            array("value" => "fa-github-square", "label" => "Github Square", "icon" => "icon-github-square"),
            array("value" => "fa-gitlab", "label" => "Gitlab", "icon" => "icon-gitlab"),
            array("value" => "fa-glass", "label" => "Glass", "icon" => "icon-glass"),
            array("value" => "fa-glide", "label" => "Glide", "icon" => "icon-glide"),
            array("value" => "fa-glide-g", "label" => "Glide G", "icon" => "icon-glide-g"),
            array("value" => "fa-globe", "label" => "Globe", "icon" => "icon-globe"),
            array("value" => "fa-google", "label" => "Google", "icon" => "icon-google"),
            array("value" => "fa-google-plus", "label" => "Google Plus", "icon" => "icon-google-plus"),
            array("value" => "fa-google-plus-official", "label" => "Google Plus Official", "icon" => "icon-google-plus-official"),
            array("value" => "fa-google-plus-square", "label" => "Google Plus Square", "icon" => "icon-google-plus-square"),
            array("value" => "fa-google-wallet", "label" => "Google Wallet", "icon" => "icon-google-wallet"),
            array("value" => "fa-graduation-cap", "label" => "Graduation Cap", "icon" => "icon-graduation-cap"),
            array("value" => "fa-gratipay", "label" => "Gratipay", "icon" => "icon-gratipay"),
            array("value" => "fa-grav", "label" => "Grav", "icon" => "icon-grav"),
            array("value" => "fa-h-square", "label" => "H Square", "icon" => "icon-h-square"),
            array("value" => "fa-hacker-news", "label" => "Hacker News", "icon" => "icon-hacker-news"),
            array("value" => "fa-hand-lizard-o", "label" => "Hand Lizard O", "icon" => "icon-hand-lizard-o"),
            array("value" => "fa-hand-o-down", "label" => "Hand O Down", "icon" => "icon-hand-o-down"),
            array("value" => "fa-hand-o-left", "label" => "Hand O Left", "icon" => "icon-hand-o-left"),
            array("value" => "fa-hand-o-right", "label" => "Hand O Right", "icon" => "icon-hand-o-right"),
            array("value" => "fa-hand-o-up", "label" => "Hand O Up", "icon" => "icon-hand-o-up"),
            array("value" => "fa-hand-paper-o", "label" => "Hand Paper O", "icon" => "icon-hand-paper-o"),
            array("value" => "fa-hand-peace-o", "label" => "Hand Peace O", "icon" => "icon-hand-peace-o"),
            array("value" => "fa-hand-pointer-o", "label" => "Hand Pointer O", "icon" => "icon-hand-pointer-o"),
            array("value" => "fa-hand-rock-o", "label" => "Hand Rock O", "icon" => "icon-hand-rock-o"),
            array("value" => "fa-hand-scissors-o", "label" => "Hand Scissors O", "icon" => "icon-hand-scissors-o"),
            array("value" => "fa-hand-spock-o", "label" => "Hand Spock O", "icon" => "icon-hand-spock-o"),
            array("value" => "fa-handshake-o", "label" => "Handshake O", "icon" => "icon-handshake-o"),
            array("value" => "fa-hashtag", "label" => "Hashtag", "icon" => "icon-hashtag"),
            array("value" => "fa-hdd-o", "label" => "Hdd O", "icon" => "icon-hdd-o"),
            array("value" => "fa-header", "label" => "Header", "icon" => "icon-header"),
            array("value" => "fa-headphones", "label" => "Headphones", "icon" => "icon-headphones"),
            array("value" => "fa-heart", "label" => "Heart", "icon" => "icon-heart"),
            array("value" => "fa-heart-o", "label" => "Heart O", "icon" => "icon-heart-o"),
            array("value" => "fa-heartbeat", "label" => "Heartbeat", "icon" => "icon-heartbeat"),
            array("value" => "fa-history", "label" => "History", "icon" => "icon-history"),
            array("value" => "fa-home", "label" => "Home", "icon" => "icon-home"),
            array("value" => "fa-hospital-o", "label" => "Hospital O", "icon" => "icon-hospital-o"),
            array("value" => "fa-hourglass", "label" => "Hourglass", "icon" => "icon-hourglass"),
            array("value" => "fa-hourglass-end", "label" => "Hourglass End", "icon" => "icon-hourglass-end"),
            array("value" => "fa-hourglass-half", "label" => "Hourglass Half", "icon" => "icon-hourglass-half"),
            array("value" => "fa-hourglass-o", "label" => "Hourglass O", "icon" => "icon-hourglass-o"),
            array("value" => "fa-hourglass-start", "label" => "Hourglass Start", "icon" => "icon-hourglass-start"),
            array("value" => "fa-houzz", "label" => "Houzz", "icon" => "icon-houzz"),
            array("value" => "fa-html5", "label" => "Html5", "icon" => "icon-html5"),
            array("value" => "fa-i-cursor", "label" => "I Cursor", "icon" => "icon-i-cursor"),
            array("value" => "fa-id-badge", "label" => "Id Badge", "icon" => "icon-id-badge"),
            array("value" => "fa-id-card", "label" => "Id Card", "icon" => "icon-id-card"),
            array("value" => "fa-id-card-o", "label" => "Id Card O", "icon" => "icon-id-card-o"),
            array("value" => "fa-ils", "label" => "Ils", "icon" => "icon-ils"),
            array("value" => "fa-imdb", "label" => "Imdb", "icon" => "icon-imdb"),
            array("value" => "fa-inbox", "label" => "Inbox", "icon" => "icon-inbox"),
            array("value" => "fa-indent", "label" => "Indent", "icon" => "icon-indent"),
            array("value" => "fa-industry", "label" => "Industry", "icon" => "icon-industry"),
            array("value" => "fa-info", "label" => "Info", "icon" => "icon-info"),
            array("value" => "fa-info-circle", "label" => "Info Circle", "icon" => "icon-info-circle"),
            array("value" => "fa-inr", "label" => "Inr", "icon" => "icon-inr"),
            array("value" => "fa-instagram", "label" => "Instagram", "icon" => "icon-instagram"),
            array("value" => "fa-internet-explorer", "label" => "Internet Explorer", "icon" => "icon-internet-explorer"),
            array("value" => "fa-ioxhost", "label" => "Ioxhost", "icon" => "icon-ioxhost"),
            array("value" => "fa-italic", "label" => "Italic", "icon" => "icon-italic"),
            array("value" => "fa-joomla", "label" => "Joomla", "icon" => "icon-joomla"),
            array("value" => "fa-jpy", "label" => "Jpy", "icon" => "icon-jpy"),
            array("value" => "fa-jsfiddle", "label" => "Jsfiddle", "icon" => "icon-jsfiddle"),
            array("value" => "fa-key", "label" => "Key", "icon" => "icon-key"),
            array("value" => "fa-keyboard-o", "label" => "Keyboard O", "icon" => "icon-keyboard-o"),
            array("value" => "fa-krw", "label" => "Krw", "icon" => "icon-krw"),
            array("value" => "fa-language", "label" => "Language", "icon" => "icon-language"),
            array("value" => "fa-laptop", "label" => "Laptop", "icon" => "icon-laptop"),
            array("value" => "fa-lastfm", "label" => "Lastfm", "icon" => "icon-lastfm"),
            array("value" => "fa-lastfm-square", "label" => "Lastfm Square", "icon" => "icon-lastfm-square"),
            array("value" => "fa-leaf", "label" => "Leaf", "icon" => "icon-leaf"),
            array("value" => "fa-leanpub", "label" => "Leanpub", "icon" => "icon-leanpub"),
            array("value" => "fa-lemon-o", "label" => "Lemon O", "icon" => "icon-lemon-o"),
            array("value" => "fa-level-down", "label" => "Level Down", "icon" => "icon-level-down"),
            array("value" => "fa-level-up", "label" => "Level Up", "icon" => "icon-level-up"),
            array("value" => "fa-life-ring", "label" => "Life Ring", "icon" => "icon-life-ring"),
            array("value" => "fa-lightbulb-o", "label" => "Lightbulb O", "icon" => "icon-lightbulb-o"),
            array("value" => "fa-line-chart", "label" => "Line Chart", "icon" => "icon-line-chart"),
            array("value" => "fa-link", "label" => "Link", "icon" => "icon-link"),
            array("value" => "fa-linkedin", "label" => "Linkedin", "icon" => "icon-linkedin"),
            array("value" => "fa-linkedin-square", "label" => "Linkedin Square", "icon" => "icon-linkedin-square"),
            array("value" => "fa-linode", "label" => "Linode", "icon" => "icon-linode"),
            array("value" => "fa-linux", "label" => "Linux", "icon" => "icon-linux"),
            array("value" => "fa-list", "label" => "List", "icon" => "icon-list"),
            array("value" => "fa-list-alt", "label" => "List Alt", "icon" => "icon-list-alt"),
            array("value" => "fa-list-ol", "label" => "List Ol", "icon" => "icon-list-ol"),
            array("value" => "fa-list-ul", "label" => "List Ul", "icon" => "icon-list-ul"),
            array("value" => "fa-location-arrow", "label" => "Location Arrow", "icon" => "icon-location-arrow"),
            array("value" => "fa-lock", "label" => "Lock", "icon" => "icon-lock"),
            array("value" => "fa-long-arrow-down", "label" => "Long Arrow Down", "icon" => "icon-long-arrow-down"),
            array("value" => "fa-long-arrow-left", "label" => "Long Arrow Left", "icon" => "icon-long-arrow-left"),
            array("value" => "fa-long-arrow-right", "label" => "Long Arrow Right", "icon" => "icon-long-arrow-right"),
            array("value" => "fa-long-arrow-up", "label" => "Long Arrow Up", "icon" => "icon-long-arrow-up"),
            array("value" => "fa-low-vision", "label" => "Low Vision", "icon" => "icon-low-vision"),
            array("value" => "fa-magic", "label" => "Magic", "icon" => "icon-magic"),
            array("value" => "fa-magnet", "label" => "Magnet", "icon" => "icon-magnet"),
            array("value" => "fa-male", "label" => "Male", "icon" => "icon-male"),
            array("value" => "fa-map", "label" => "Map", "icon" => "icon-map"),
            array("value" => "fa-map-marker", "label" => "Map Marker", "icon" => "icon-map-marker"),
            array("value" => "fa-map-o", "label" => "Map O", "icon" => "icon-map-o"),
            array("value" => "fa-map-pin", "label" => "Map Pin", "icon" => "icon-map-pin"),
            array("value" => "fa-map-signs", "label" => "Map Signs", "icon" => "icon-map-signs"),
            array("value" => "fa-mars", "label" => "Mars", "icon" => "icon-mars"),
            array("value" => "fa-mars-double", "label" => "Mars Double", "icon" => "icon-mars-double"),
            array("value" => "fa-mars-stroke", "label" => "Mars Stroke", "icon" => "icon-mars-stroke"),
            array("value" => "fa-mars-stroke-h", "label" => "Mars Stroke H", "icon" => "icon-mars-stroke-h"),
            array("value" => "fa-mars-stroke-v", "label" => "Mars Stroke V", "icon" => "icon-mars-stroke-v"),
            array("value" => "fa-maxcdn", "label" => "Maxcdn", "icon" => "icon-maxcdn"),
            array("value" => "fa-meanpath", "label" => "Meanpath", "icon" => "icon-meanpath"),
            array("value" => "fa-medium", "label" => "Medium", "icon" => "icon-medium"),
            array("value" => "fa-medkit", "label" => "Medkit", "icon" => "icon-medkit"),
            array("value" => "fa-meetup", "label" => "Meetup", "icon" => "icon-meetup"),
            array("value" => "fa-meh-o", "label" => "Meh O", "icon" => "icon-meh-o"),
            array("value" => "fa-mercury", "label" => "Mercury", "icon" => "icon-mercury"),
            array("value" => "fa-microchip", "label" => "Microchip", "icon" => "icon-microchip"),
            array("value" => "fa-microphone", "label" => "Microphone", "icon" => "icon-microphone"),
            array("value" => "fa-microphone-slash", "label" => "Microphone Slash", "icon" => "icon-microphone-slash"),
            array("value" => "fa-minus", "label" => "Minus", "icon" => "icon-minus"),
            array("value" => "fa-minus-circle", "label" => "Minus Circle", "icon" => "icon-minus-circle"),
            array("value" => "fa-minus-square", "label" => "Minus Square", "icon" => "icon-minus-square"),
            array("value" => "fa-minus-square-o", "label" => "Minus Square O", "icon" => "icon-minus-square-o"),
            array("value" => "fa-mixcloud", "label" => "Mixcloud", "icon" => "icon-mixcloud"),
            array("value" => "fa-mobile", "label" => "Mobile", "icon" => "icon-mobile"),
            array("value" => "fa-modx", "label" => "Modx", "icon" => "icon-modx"),
            array("value" => "fa-money", "label" => "Money", "icon" => "icon-money"),
            array("value" => "fa-moon-o", "label" => "Moon O", "icon" => "icon-moon-o"),
            array("value" => "fa-motorcycle", "label" => "Motorcycle", "icon" => "icon-motorcycle"),
            array("value" => "fa-mouse-pointer", "label" => "Mouse Pointer", "icon" => "icon-mouse-pointer"),
            array("value" => "fa-music", "label" => "Music", "icon" => "icon-music"),
            array("value" => "fa-neuter", "label" => "Neuter", "icon" => "icon-neuter"),
            array("value" => "fa-newspaper-o", "label" => "Newspaper O", "icon" => "icon-newspaper-o"),
            array("value" => "fa-object-group", "label" => "Object Group", "icon" => "icon-object-group"),
            array("value" => "fa-object-ungroup", "label" => "Object Ungroup", "icon" => "icon-object-ungroup"),
            array("value" => "fa-odnoklassniki", "label" => "Odnoklassniki", "icon" => "icon-odnoklassniki"),
            array("value" => "fa-odnoklassniki-square", "label" => "Odnoklassniki Square", "icon" => "icon-odnoklassniki-square"),
            array("value" => "fa-opencart", "label" => "Opencart", "icon" => "icon-opencart"),
            array("value" => "fa-openid", "label" => "Openid", "icon" => "icon-openid"),
            array("value" => "fa-opera", "label" => "Opera", "icon" => "icon-opera"),
            array("value" => "fa-optin-monster", "label" => "Optin Monster", "icon" => "icon-optin-monster"),
            array("value" => "fa-outdent", "label" => "Outdent", "icon" => "icon-outdent"),
            array("value" => "fa-pagelines", "label" => "Pagelines", "icon" => "icon-pagelines"),
            array("value" => "fa-paint-brush", "label" => "Paint Brush", "icon" => "icon-paint-brush"),
            array("value" => "fa-paper-plane", "label" => "Paper Plane", "icon" => "icon-paper-plane"),
            array("value" => "fa-paper-plane-o", "label" => "Paper Plane O", "icon" => "icon-paper-plane-o"),
            array("value" => "fa-paperclip", "label" => "Paperclip", "icon" => "icon-paperclip"),
            array("value" => "fa-paragraph", "label" => "Paragraph", "icon" => "icon-paragraph"),
            array("value" => "fa-pause", "label" => "Pause", "icon" => "icon-pause"),
            array("value" => "fa-pause-circle", "label" => "Pause Circle", "icon" => "icon-pause-circle"),
            array("value" => "fa-pause-circle-o", "label" => "Pause Circle O", "icon" => "icon-pause-circle-o"),
            array("value" => "fa-paw", "label" => "Paw", "icon" => "icon-paw"),
            array("value" => "fa-paypal", "label" => "Paypal", "icon" => "icon-paypal"),
            array("value" => "fa-pencil", "label" => "Pencil", "icon" => "icon-pencil"),
            array("value" => "fa-pencil-square", "label" => "Pencil Square", "icon" => "icon-pencil-square"),
            array("value" => "fa-pencil-square-o", "label" => "Pencil Square O", "icon" => "icon-pencil-square-o"),
            array("value" => "fa-percent", "label" => "Percent", "icon" => "icon-percent"),
            array("value" => "fa-phone", "label" => "Phone", "icon" => "icon-phone"),
            array("value" => "fa-phone-square", "label" => "Phone Square", "icon" => "icon-phone-square"),
            array("value" => "fa-picture-o", "label" => "Picture O", "icon" => "icon-picture-o"),
            array("value" => "fa-pie-chart", "label" => "Pie Chart", "icon" => "icon-pie-chart"),
            array("value" => "fa-pied-piper", "label" => "Pied Piper", "icon" => "icon-pied-piper"),
            array("value" => "fa-pied-piper-alt", "label" => "Pied Piper Alt", "icon" => "icon-pied-piper-alt"),
            array("value" => "fa-pied-piper-pp", "label" => "Pied Piper Pp", "icon" => "icon-pied-piper-pp"),
            array("value" => "fa-pinterest", "label" => "Pinterest", "icon" => "icon-pinterest"),
            array("value" => "fa-pinterest-p", "label" => "Pinterest P", "icon" => "icon-pinterest-p"),
            array("value" => "fa-pinterest-square", "label" => "Pinterest Square", "icon" => "icon-pinterest-square"),
            array("value" => "fa-plane", "label" => "Plane", "icon" => "icon-plane"),
            array("value" => "fa-play", "label" => "Play", "icon" => "icon-play"),
            array("value" => "fa-play-circle", "label" => "Play Circle", "icon" => "icon-play-circle"),
            array("value" => "fa-play-circle-o", "label" => "Play Circle O", "icon" => "icon-play-circle-o"),
            array("value" => "fa-plug", "label" => "Plug", "icon" => "icon-plug"),
            array("value" => "fa-plus", "label" => "Plus", "icon" => "icon-plus"),
            array("value" => "fa-plus-circle", "label" => "Plus Circle", "icon" => "icon-plus-circle"),
            array("value" => "fa-plus-square", "label" => "Plus Square", "icon" => "icon-plus-square"),
            array("value" => "fa-plus-square-o", "label" => "Plus Square O", "icon" => "icon-plus-square-o"),
            array("value" => "fa-podcast", "label" => "Podcast", "icon" => "icon-podcast"),
            array("value" => "fa-power-off", "label" => "Power Off", "icon" => "icon-power-off"),
            array("value" => "fa-print", "label" => "Print", "icon" => "icon-print"),
            array("value" => "fa-product-hunt", "label" => "Product Hunt", "icon" => "icon-product-hunt"),
            array("value" => "fa-puzzle-piece", "label" => "Puzzle Piece", "icon" => "icon-puzzle-piece"),
            array("value" => "fa-qq", "label" => "Qq", "icon" => "icon-qq"),
            array("value" => "fa-qrcode", "label" => "Qrcode", "icon" => "icon-qrcode"),
            array("value" => "fa-question", "label" => "Question", "icon" => "icon-question"),
            array("value" => "fa-question-circle", "label" => "Question Circle", "icon" => "icon-question-circle"),
            array("value" => "fa-question-circle-o", "label" => "Question Circle O", "icon" => "icon-question-circle-o"),
            array("value" => "fa-quora", "label" => "Quora", "icon" => "icon-quora"),
            array("value" => "fa-quote-left", "label" => "Quote Left", "icon" => "icon-quote-left"),
            array("value" => "fa-quote-right", "label" => "Quote Right", "icon" => "icon-quote-right"),
            array("value" => "fa-random", "label" => "Random", "icon" => "icon-random"),
            array("value" => "fa-ravelry", "label" => "Ravelry", "icon" => "icon-ravelry"),
            array("value" => "fa-rebel", "label" => "Rebel", "icon" => "icon-rebel"),
            array("value" => "fa-recycle", "label" => "Recycle", "icon" => "icon-recycle"),
            array("value" => "fa-reddit", "label" => "Reddit", "icon" => "icon-reddit"),
            array("value" => "fa-reddit-alien", "label" => "Reddit Alien", "icon" => "icon-reddit-alien"),
            array("value" => "fa-reddit-square", "label" => "Reddit Square", "icon" => "icon-reddit-square"),
            array("value" => "fa-refresh", "label" => "Refresh", "icon" => "icon-refresh"),
            array("value" => "fa-registered", "label" => "Registered", "icon" => "icon-registered"),
            array("value" => "fa-renren", "label" => "Renren", "icon" => "icon-renren"),
            array("value" => "fa-repeat", "label" => "Repeat", "icon" => "icon-repeat"),
            array("value" => "fa-reply", "label" => "Reply", "icon" => "icon-reply"),
            array("value" => "fa-reply-all", "label" => "Reply All", "icon" => "icon-reply-all"),
            array("value" => "fa-retweet", "label" => "Retweet", "icon" => "icon-retweet"),
            array("value" => "fa-road", "label" => "Road", "icon" => "icon-road"),
            array("value" => "fa-rocket", "label" => "Rocket", "icon" => "icon-rocket"),
            array("value" => "fa-rss", "label" => "Rss", "icon" => "icon-rss"),
            array("value" => "fa-rss-square", "label" => "Rss Square", "icon" => "icon-rss-square"),
            array("value" => "fa-rub", "label" => "Rub", "icon" => "icon-rub"),
            array("value" => "fa-safari", "label" => "Safari", "icon" => "icon-safari"),
            array("value" => "fa-scissors", "label" => "Scissors", "icon" => "icon-scissors"),
            array("value" => "fa-scribd", "label" => "Scribd", "icon" => "icon-scribd"),
            array("value" => "fa-search", "label" => "Search", "icon" => "icon-search"),
            array("value" => "fa-search-minus", "label" => "Search Minus", "icon" => "icon-search-minus"),
            array("value" => "fa-search-plus", "label" => "Search Plus", "icon" => "icon-search-plus"),
            array("value" => "fa-sellsy", "label" => "Sellsy", "icon" => "icon-sellsy"),
            array("value" => "fa-server", "label" => "Server", "icon" => "icon-server"),
            array("value" => "fa-share", "label" => "Share", "icon" => "icon-share"),
            array("value" => "fa-share-alt", "label" => "Share Alt", "icon" => "icon-share-alt"),
            array("value" => "fa-share-alt-square", "label" => "Share Alt Square", "icon" => "icon-share-alt-square"),
            array("value" => "fa-share-square", "label" => "Share Square", "icon" => "icon-share-square"),
            array("value" => "fa-share-square-o", "label" => "Share Square O", "icon" => "icon-share-square-o"),
            array("value" => "fa-shield", "label" => "Shield", "icon" => "icon-shield"),
            array("value" => "fa-ship", "label" => "Ship", "icon" => "icon-ship"),
            array("value" => "fa-shirtsinbulk", "label" => "Shirtsinbulk", "icon" => "icon-shirtsinbulk"),
            array("value" => "fa-shopping-bag", "label" => "Shopping Bag", "icon" => "icon-shopping-bag"),
            array("value" => "fa-shopping-basket", "label" => "Shopping Basket", "icon" => "icon-shopping-basket"),
            array("value" => "fa-shopping-cart", "label" => "Shopping Cart", "icon" => "icon-shopping-cart"),
            array("value" => "fa-shower", "label" => "Shower", "icon" => "icon-shower"),
            array("value" => "fa-sign-in", "label" => "Sign In", "icon" => "icon-sign-in"),
            array("value" => "fa-sign-language", "label" => "Sign Language", "icon" => "icon-sign-language"),
            array("value" => "fa-sign-out", "label" => "Sign Out", "icon" => "icon-sign-out"),
            array("value" => "fa-signal", "label" => "Signal", "icon" => "icon-signal"),
            array("value" => "fa-simplybuilt", "label" => "Simplybuilt", "icon" => "icon-simplybuilt"),
            array("value" => "fa-sitemap", "label" => "Sitemap", "icon" => "icon-sitemap"),
            array("value" => "fa-skyatlas", "label" => "Skyatlas", "icon" => "icon-skyatlas"),
            array("value" => "fa-skype", "label" => "Skype", "icon" => "icon-skype"),
            array("value" => "fa-slack", "label" => "Slack", "icon" => "icon-slack"),
            array("value" => "fa-sliders", "label" => "Sliders", "icon" => "icon-sliders"),
            array("value" => "fa-slideshare", "label" => "Slideshare", "icon" => "icon-slideshare"),
            array("value" => "fa-smile-o", "label" => "Smile O", "icon" => "icon-smile-o"),
            array("value" => "fa-snapchat", "label" => "Snapchat", "icon" => "icon-snapchat"),
            array("value" => "fa-snapchat-ghost", "label" => "Snapchat Ghost", "icon" => "icon-snapchat-ghost"),
            array("value" => "fa-snapchat-square", "label" => "Snapchat Square", "icon" => "icon-snapchat-square"),
            array("value" => "fa-snowflake-o", "label" => "Snowflake O", "icon" => "icon-snowflake-o"),
            array("value" => "fa-sort", "label" => "Sort", "icon" => "icon-sort"),
            array("value" => "fa-sort-alpha-asc", "label" => "Sort Alpha Asc", "icon" => "icon-sort-alpha-asc"),
            array("value" => "fa-sort-alpha-desc", "label" => "Sort Alpha Desc", "icon" => "icon-sort-alpha-desc"),
            array("value" => "fa-sort-amount-asc", "label" => "Sort Amount Asc", "icon" => "icon-sort-amount-asc"),
            array("value" => "fa-sort-amount-desc", "label" => "Sort Amount Desc", "icon" => "icon-sort-amount-desc"),
            array("value" => "fa-sort-asc", "label" => "Sort Asc", "icon" => "icon-sort-asc"),
            array("value" => "fa-sort-desc", "label" => "Sort Desc", "icon" => "icon-sort-desc"),
            array("value" => "fa-sort-numeric-asc", "label" => "Sort Numeric Asc", "icon" => "icon-sort-numeric-asc"),
            array("value" => "fa-sort-numeric-desc", "label" => "Sort Numeric Desc", "icon" => "icon-sort-numeric-desc"),
            array("value" => "fa-soundcloud", "label" => "Soundcloud", "icon" => "icon-soundcloud"),
            array("value" => "fa-space-shuttle", "label" => "Space Shuttle", "icon" => "icon-space-shuttle"),
            array("value" => "fa-spinner", "label" => "Spinner", "icon" => "icon-spinner"),
            array("value" => "fa-spoon", "label" => "Spoon", "icon" => "icon-spoon"),
            array("value" => "fa-spotify", "label" => "Spotify", "icon" => "icon-spotify"),
            array("value" => "fa-square", "label" => "Square", "icon" => "icon-square"),
            array("value" => "fa-square-o", "label" => "Square O", "icon" => "icon-square-o"),
            array("value" => "fa-stack-exchange", "label" => "Stack Exchange", "icon" => "icon-stack-exchange"),
            array("value" => "fa-stack-overflow", "label" => "Stack Overflow", "icon" => "icon-stack-overflow"),
            array("value" => "fa-star", "label" => "Star", "icon" => "icon-star"),
            array("value" => "fa-star-half", "label" => "Star Half", "icon" => "icon-star-half"),
            array("value" => "fa-star-half-o", "label" => "Star Half O", "icon" => "icon-star-half-o"),
            array("value" => "fa-star-o", "label" => "Star O", "icon" => "icon-star-o"),
            array("value" => "fa-steam", "label" => "Steam", "icon" => "icon-steam"),
            array("value" => "fa-steam-square", "label" => "Steam Square", "icon" => "icon-steam-square"),
            array("value" => "fa-step-backward", "label" => "Step Backward", "icon" => "icon-step-backward"),
            array("value" => "fa-step-forward", "label" => "Step Forward", "icon" => "icon-step-forward"),
            array("value" => "fa-stethoscope", "label" => "Stethoscope", "icon" => "icon-stethoscope"),
            array("value" => "fa-sticky-note", "label" => "Sticky Note", "icon" => "icon-sticky-note"),
            array("value" => "fa-sticky-note-o", "label" => "Sticky Note O", "icon" => "icon-sticky-note-o"),
            array("value" => "fa-stop", "label" => "Stop", "icon" => "icon-stop"),
            array("value" => "fa-stop-circle", "label" => "Stop Circle", "icon" => "icon-stop-circle"),
            array("value" => "fa-stop-circle-o", "label" => "Stop Circle O", "icon" => "icon-stop-circle-o"),
            array("value" => "fa-street-view", "label" => "Street View", "icon" => "icon-street-view"),
            array("value" => "fa-strikethrough", "label" => "Strikethrough", "icon" => "icon-strikethrough"),
            array("value" => "fa-stumbleupon", "label" => "Stumbleupon", "icon" => "icon-stumbleupon"),
            array("value" => "fa-stumbleupon-circle", "label" => "Stumbleupon Circle", "icon" => "icon-stumbleupon-circle"),
            array("value" => "fa-subscript", "label" => "Subscript", "icon" => "icon-subscript"),
            array("value" => "fa-subway", "label" => "Subway", "icon" => "icon-subway"),
            array("value" => "fa-suitcase", "label" => "Suitcase", "icon" => "icon-suitcase"),
            array("value" => "fa-sun-o", "label" => "Sun O", "icon" => "icon-sun-o"),
            array("value" => "fa-superpowers", "label" => "Superpowers", "icon" => "icon-superpowers"),
            array("value" => "fa-superscript", "label" => "Superscript", "icon" => "icon-superscript"),
            array("value" => "fa-table", "label" => "Table", "icon" => "icon-table"),
            array("value" => "fa-tablet", "label" => "Tablet", "icon" => "icon-tablet"),
            array("value" => "fa-tachometer", "label" => "Tachometer", "icon" => "icon-tachometer"),
            array("value" => "fa-tag", "label" => "Tag", "icon" => "icon-tag"),
            array("value" => "fa-tags", "label" => "Tags", "icon" => "icon-tags"),
            array("value" => "fa-tasks", "label" => "Tasks", "icon" => "icon-tasks"),
            array("value" => "fa-taxi", "label" => "Taxi", "icon" => "icon-taxi"),
            array("value" => "fa-telegram", "label" => "Telegram", "icon" => "icon-telegram"),
            array("value" => "fa-television", "label" => "Television", "icon" => "icon-television"),
            array("value" => "fa-tencent-weibo", "label" => "Tencent Weibo", "icon" => "icon-tencent-weibo"),
            array("value" => "fa-terminal", "label" => "Terminal", "icon" => "icon-terminal"),
            array("value" => "fa-text-height", "label" => "Text Height", "icon" => "icon-text-height"),
            array("value" => "fa-text-width", "label" => "Text Width", "icon" => "icon-text-width"),
            array("value" => "fa-th", "label" => "Th", "icon" => "icon-th"),
            array("value" => "fa-th-large", "label" => "Th Large", "icon" => "icon-th-large"),
            array("value" => "fa-th-list", "label" => "Th List", "icon" => "icon-th-list"),
            array("value" => "fa-themeisle", "label" => "Themeisle", "icon" => "icon-themeisle"),
            array("value" => "fa-thermometer-empty", "label" => "Thermometer Empty", "icon" => "icon-thermometer-empty"),
            array("value" => "fa-thermometer-full", "label" => "Thermometer Full", "icon" => "icon-thermometer-full"),
            array("value" => "fa-thermometer-half", "label" => "Thermometer Half", "icon" => "icon-thermometer-half"),
            array("value" => "fa-thermometer-quarter", "label" => "Thermometer Quarter", "icon" => "icon-thermometer-quarter"),
            array("value" => "fa-thermometer-three-quarters", "label" => "Thermometer Three Quarters", "icon" => "icon-thermometer-three-quarters"),
            array("value" => "fa-thumb-tack", "label" => "Thumb Tack", "icon" => "icon-thumb-tack"),
            array("value" => "fa-thumbs-down", "label" => "Thumbs Down", "icon" => "icon-thumbs-down"),
            array("value" => "fa-thumbs-o-down", "label" => "Thumbs O Down", "icon" => "icon-thumbs-o-down"),
            array("value" => "fa-thumbs-o-up", "label" => "Thumbs O Up", "icon" => "icon-thumbs-o-up"),
            array("value" => "fa-thumbs-up", "label" => "Thumbs Up", "icon" => "icon-thumbs-up"),
            array("value" => "fa-ticket", "label" => "Ticket", "icon" => "icon-ticket"),
            array("value" => "fa-times", "label" => "Times", "icon" => "icon-times"),
            array("value" => "fa-times-circle", "label" => "Times Circle", "icon" => "icon-times-circle"),
            array("value" => "fa-times-circle-o", "label" => "Times Circle O", "icon" => "icon-times-circle-o"),
            array("value" => "fa-tint", "label" => "Tint", "icon" => "icon-tint"),
            array("value" => "fa-toggle-off", "label" => "Toggle Off", "icon" => "icon-toggle-off"),
            array("value" => "fa-toggle-on", "label" => "Toggle On", "icon" => "icon-toggle-on"),
            array("value" => "fa-trademark", "label" => "Trademark", "icon" => "icon-trademark"),
            array("value" => "fa-train", "label" => "Train", "icon" => "icon-train"),
            array("value" => "fa-transgender", "label" => "Transgender", "icon" => "icon-transgender"),
            array("value" => "fa-transgender-alt", "label" => "Transgender Alt", "icon" => "icon-transgender-alt"),
            array("value" => "fa-trash", "label" => "Trash", "icon" => "icon-trash"),
            array("value" => "fa-trash-o", "label" => "Trash O", "icon" => "icon-trash-o"),
            array("value" => "fa-tree", "label" => "Tree", "icon" => "icon-tree"),
            array("value" => "fa-trello", "label" => "Trello", "icon" => "icon-trello"),
            array("value" => "fa-tripadvisor", "label" => "Tripadvisor", "icon" => "icon-tripadvisor"),
            array("value" => "fa-trophy", "label" => "Trophy", "icon" => "icon-trophy"),
            array("value" => "fa-truck", "label" => "Truck", "icon" => "icon-truck"),
            array("value" => "fa-try", "label" => "Try", "icon" => "icon-try"),
            array("value" => "fa-tty", "label" => "Tty", "icon" => "icon-tty"),
            array("value" => "fa-tumblr", "label" => "Tumblr", "icon" => "icon-tumblr"),
            array("value" => "fa-tumblr-square", "label" => "Tumblr Square", "icon" => "icon-tumblr-square"),
            array("value" => "fa-twitch", "label" => "Twitch", "icon" => "icon-twitch"),
            array("value" => "fa-twitter", "label" => "Twitter", "icon" => "icon-twitter"),
            array("value" => "fa-twitter-square", "label" => "Twitter Square", "icon" => "icon-twitter-square"),
            array("value" => "fa-umbrella", "label" => "Umbrella", "icon" => "icon-umbrella"),
            array("value" => "fa-underline", "label" => "Underline", "icon" => "icon-underline"),
            array("value" => "fa-undo", "label" => "Undo", "icon" => "icon-undo"),
            array("value" => "fa-universal-access", "label" => "Universal Access", "icon" => "icon-universal-access"),
            array("value" => "fa-university", "label" => "University", "icon" => "icon-university"),
            array("value" => "fa-unlock", "label" => "Unlock", "icon" => "icon-unlock"),
            array("value" => "fa-unlock-alt", "label" => "Unlock Alt", "icon" => "icon-unlock-alt"),
            array("value" => "fa-upload", "label" => "Upload", "icon" => "icon-upload"),
            array("value" => "fa-usb", "label" => "Usb", "icon" => "icon-usb"),
            array("value" => "fa-usd", "label" => "Usd", "icon" => "icon-usd"),
            array("value" => "fa-user", "label" => "User", "icon" => "icon-user"),
            array("value" => "fa-user-circle", "label" => "User Circle", "icon" => "icon-user-circle"),
            array("value" => "fa-user-circle-o", "label" => "User Circle O", "icon" => "icon-user-circle-o"),
            array("value" => "fa-user-md", "label" => "User Md", "icon" => "icon-user-md"),
            array("value" => "fa-user-o", "label" => "User O", "icon" => "icon-user-o"),
            array("value" => "fa-user-plus", "label" => "User Plus", "icon" => "icon-user-plus"),
            array("value" => "fa-user-secret", "label" => "User Secret", "icon" => "icon-user-secret"),
            array("value" => "fa-user-times", "label" => "User Times", "icon" => "icon-user-times"),
            array("value" => "fa-users", "label" => "Users", "icon" => "icon-users"),
            array("value" => "fa-venus", "label" => "Venus", "icon" => "icon-venus"),
            array("value" => "fa-venus-double", "label" => "Venus Double", "icon" => "icon-venus-double"),
            array("value" => "fa-venus-mars", "label" => "Venus Mars", "icon" => "icon-venus-mars"),
            array("value" => "fa-viacoin", "label" => "Viacoin", "icon" => "icon-viacoin"),
            array("value" => "fa-viadeo", "label" => "Viadeo", "icon" => "icon-viadeo"),
            array("value" => "fa-viadeo-square", "label" => "Viadeo Square", "icon" => "icon-viadeo-square"),
            array("value" => "fa-video-camera", "label" => "Video Camera", "icon" => "icon-video-camera"),
            array("value" => "fa-vimeo", "label" => "Vimeo", "icon" => "icon-vimeo"),
            array("value" => "fa-vimeo-square", "label" => "Vimeo Square", "icon" => "icon-vimeo-square"),
            array("value" => "fa-vine", "label" => "Vine", "icon" => "icon-vine"),
            array("value" => "fa-vk", "label" => "Vk", "icon" => "icon-vk"),
            array("value" => "fa-volume-control-phone", "label" => "Volume Control Phone", "icon" => "icon-volume-control-phone"),
            array("value" => "fa-volume-down", "label" => "Volume Down", "icon" => "icon-volume-down"),
            array("value" => "fa-volume-off", "label" => "Volume Off", "icon" => "icon-volume-off"),
            array("value" => "fa-volume-up", "label" => "Volume Up", "icon" => "icon-volume-up"),
            array("value" => "fa-weibo", "label" => "Weibo", "icon" => "icon-weibo"),
            array("value" => "fa-weixin", "label" => "Weixin", "icon" => "icon-weixin"),
            array("value" => "fa-whatsapp", "label" => "Whatsapp", "icon" => "icon-whatsapp"),
            array("value" => "fa-wheelchair", "label" => "Wheelchair", "icon" => "icon-wheelchair"),
            array("value" => "fa-wheelchair-alt", "label" => "Wheelchair Alt", "icon" => "icon-wheelchair-alt"),
            array("value" => "fa-wifi", "label" => "Wifi", "icon" => "icon-wifi"),
            array("value" => "fa-wikipedia-w", "label" => "Wikipedia W", "icon" => "icon-wikipedia-w"),
            array("value" => "fa-window-close", "label" => "Window Close", "icon" => "icon-window-close"),
            array("value" => "fa-window-close-o", "label" => "Window Close O", "icon" => "icon-window-close-o"),
            array("value" => "fa-window-maximize", "label" => "Window Maximize", "icon" => "icon-window-maximize"),
            array("value" => "fa-window-minimize", "label" => "Window Minimize", "icon" => "icon-window-minimize"),
            array("value" => "fa-window-restore", "label" => "Window Restore", "icon" => "icon-window-restore"),
            array("value" => "fa-windows", "label" => "Windows", "icon" => "icon-windows"),
            array("value" => "fa-wordpress", "label" => "Wordpress", "icon" => "icon-wordpress"),
            array("value" => "fa-wpbeginner", "label" => "Wpbeginner", "icon" => "icon-wpbeginner"),
            array("value" => "fa-wpexplorer", "label" => "Wpexplorer", "icon" => "icon-wpexplorer"),
            array("value" => "fa-wpforms", "label" => "Wpforms", "icon" => "icon-wpforms"),
            array("value" => "fa-wrench", "label" => "Wrench", "icon" => "icon-wrench"),
            array("value" => "fa-xing", "label" => "Xing", "icon" => "icon-xing"),
            array("value" => "fa-xing-square", "label" => "Xing Square", "icon" => "icon-xing-square"),
            array("value" => "fa-y-combinator", "label" => "Y Combinator", "icon" => "icon-y-combinator"),
            array("value" => "fa-yahoo", "label" => "Yahoo", "icon" => "icon-yahoo"),
            array("value" => "fa-yelp", "label" => "Yelp", "icon" => "icon-yelp"),
            array("value" => "fa-yoast", "label" => "Yoast", "icon" => "icon-yoast"),
            array("value" => "fa-youtube", "label" => "Youtube", "icon" => "icon-youtube"),
            array("value" => "fa-youtube-play", "label" => "Youtube Play", "icon" => "icon-youtube-play"),
            array("value" => "fa-youtube-square", "label" => "Youtube Square", "icon" => "icon-youtube-square")
        );
    }
}